# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=50, unique=True, verbose_name='cpf')),
                ('dados_institucionais', models.CharField(max_length=60, verbose_name='Dados institucionais')),
                ('instituicao', models.CharField(blank=True, max_length=50, verbose_name='Instituição')),
                ('curso', models.CharField(blank=True, max_length=50, verbose_name='Curso')),
                ('tipo_inscricao', models.CharField(blank=True, max_length=100, verbose_name='Tipo da inscricao')),
                ('numero_tranzacao', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Numero da transação')),
                ('status_pagamento', models.BooleanField(default=False, verbose_name='Pago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
